Simplify must_gather_shell, get all args from user
RedHatQE/must-gather-explorer pull request #56
Opened 2024-12-05 12:06 UTC by myakove

2024-12-05 12:06 UTC, redhat-qe-bot2 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
    * You can add extra args to the Podman build command
        * Example: `/build-and-push-container --build-arg OPENSHIFT_PYTHON_WRAPPER_COMMIT=<commit_hash>`
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install
 * `/retest all`: Retest all

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-12-05 12:07 UTC, myakove commented
@jpeimer please verify (I verified but don't trust me)

2024-12-05 13:04 UTC, jpeimer requested changes

2024-12-05 13:04 UTC, jpeimer commented on must_gather_explorer/utils.py
>  ) -> bool:
So this function is not parsing actions anymore, maybe we could name it something like `call_action_function`?

2024-12-05 13:57 UTC, myakove commented on must_gather_explorer/prompt_handler.py
> +            if not oyaml:
done

2024-12-05 13:57 UTC, myakove commented on must_gather_explorer/utils.py
>      except MissingResourceKindAliasError:
Done

2024-12-05 13:59 UTC, myakove commented on must_gather_explorer/utils.py
>  ) -> bool:
Done

2024-12-06 10:14 UTC, myakove commented on must_gather_explorer/utils.py
> +    actions_dict[action](resources_raw_data, oyaml, yaml_fields)
Actions are managed by `MustGatherExplorerPrompt` and validated there

2024-12-06 10:40 UTC, myakove commented on must_gather_explorer/tests/test_cli.py
> +    assert not err, err
Those tests only cover the CLI args, not code functionality .
Please open issue to add functional tests

2024-12-06 13:23 UTC, myakove commented
/retest build-container

2024-12-08 09:06 UTC, jpeimer approved these changes

2024-12-08 09:13 UTC, myakove commented
@jpeimer did you check if all working? 
if so please verify and merge :)

2024-12-08 09:35 UTC, myakove commented
/verified

2024-12-08 09:36 UTC, merged

2024-12-08 11:02 UTC, jpeimer commented
@myakove yes I checked, and it looks like all is working :)